# Generated by Django 4.2.2 on 2023-06-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Важность',
                'verbose_name_plural': 'Важность',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('objective', models.CharField(max_length=256)),
                ('completed', models.BooleanField(default=False)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objectivevalue')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
